### ISSUE TITLE
Is it possible to split the code of this example?

### ISSUE THREAD

**Issue by vincent-yao27** [eddyerburgh/vue-cli-ssr-example#1]
I tried to replace the `HelloWorld` at `src/router.js:14` with `() => import('./components/HelloWorld.vue')` and comment out other `HelloWorld` import and references at `src/router.js:4`, `src/App.vue:9` and `src/App.vue:14`, then run `npm run build`.

It worked fine with a static server, but got a `ReferenceError: document is not defined` when I visited the page rendered by the server of this example started by `npm start`.

I really don't know what I did wrong, could you please give me some help?

**Comment by dayangege** [comment]
i got same problem.
please give me some help too.

**Comment by lentoo** [comment]
i got same problem.
please give me some help too.

**Comment by slidenerd** [comment]
Ideally you should split this into a client and server folder and keep relevant stuff in each

**Comment by AlanSean** [comment]
vue.config.js 添加 
 css:{
     extract:false 
  }
就好了
