### ISSUE TITLE
how to use async data ? 

### ISSUE THREAD

**Issue by mesutgok** [eddyerburgh/vue-cli-ssr-example#10]
Hi, 

how to use asyncData ? I have problem app init vuex state data.

Good works 

```
 App running at:
  - Local:   http://localhost:8001
(node:10829) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'errorMessage' of undefined
    at app.js:3606:20
(node:10829) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
 handled with .catch(). (rejection id: 716)
```

**Comment by eddyerburgh** [comment]
To add Vuex, follow the SSR guide—https://ssr.vuejs.org/guide/data.html#data-store

The structure of the compiled code in this project is the same as the example, it's just been stripped down. The server-side code is the same, except it proxies requests to the dev server if running in dev mode.

**Comment by mesutgok** [comment]
@eddyerburgh vue cli ssr plugin and axios data fetch ssr sample code share pls ?
