### ISSUE TITLE
Did you try to use element UI? I encountered a problem when I imported the 'element-ui/lib/theme-chalk/index.css'

### ISSUE THREAD

**Issue by antbaobao** [eddyerburgh/vue-cli-ssr-example#11]
Building for production...(node:16738) UnhandledPromiseRejectionWarning: Error: Server-side bundle should have one single entry file. Avoid using CommonsChunkPlugin in the server config.

**Comment by rafinskipg** [comment]
@antbaobao  you should provide an example of what you imported and how, lets see if we can help

**Comment by antbaobao** [comment]
@rafinskipg I have solved it, thanks

**Comment by eddyerburgh** [comment]
How did you solve it @antbaobao ?
