### ISSUE TITLE
vue-cli library

### ISSUE THREAD

**Issue by tiagomatosweb** [eddyerburgh/vue-cli-ssr-example#12]
Hey buddy, 
I am using vue-cli to generate npm packages and your repo has helped a lot. Tks for that.
My package should work in SSR as well as client side.
I could generate those to files separate.

Do I need to include both in my project in order to work during SSR and client side? Do you know if there is any other better approach?

Tks

**Comment by eddyerburgh** [comment]
A good method is to build two files for distribution, one that is compiled to es5 and commonJS modules, and one that's compiled to es5 using ES modules, so that module bundlers can tree shake.

Generally you shouldn't include two separate files for server and client. The code should either be universal, or explicitly for one environment or the other. If you do want different functionality on the server/client then I recommend creating two different packages.

**Comment by tiagomatosweb** [comment]
Thanks mate for your response.
I really don't need different functionality between server and client.

Currently, I am adding two separate files but I know that is not ideal and I could not figure out the best way using vue-cli.

I can see that vue-cli exports common.js and umd.js but none of those works for both server side and client.

Any clue to guide me up? 

Much appreciated.

**Comment by tiagomatosweb** [comment]
Hey mate, sorry to disturb you again.
I've got it working but the CSS is not being loaded dynamically.

If access any page that there is not the component present, and then navigate (vue-route) to the page that the component is present, the CSS is not being loaded.

Currently, I need to import the lib as well as the CSS which I think is not ideal like so

```
import Vue from 'vue';
import myLib from 'myLib';
import 'myLib/dist/myLib-ssr.css';

Vue.use(myLib);
```

Any thoughts to fix it?

Tks much apprecited

**Comment by eddyerburgh** [comment]
I think that's fine importing the CSS directly, that's how a lot of libraries work. For example, Vuetify:

>You will also need to include the Vuetify css file. Simply include the Vuetify css file in your index.html or import the actual stylus file or the minified css.

>```// index.js or main.js
import 'vuetify/dist/vuetify.min.css' // Ensure you are using css-loader```

**Comment by tiagomatosweb** [comment]
Mmm, fair enough but I've seen libraries that loads the style dynamically. I will keep digging.
Tks anyway mate
