### ISSUE TITLE
Build and serve not working under Windows

### ISSUE THREAD

**Issue by mheskol** [eddyerburgh/vue-cli-ssr-example#2]
Build and serve commands are not working under Windows.
The error is 'mv' is not a recognised command. But even after changing the `mv` command with the equivalent Windows `move` command the project is still broken in many ways with `serve` not working but only `start` which works but without hot reloading.

Any thoughts how to solve these issues?

**Comment by eddyerburgh** [comment]
Nice work @bachdgvn :)

Would you like to make a PR with the fix?

**Comment by jonaskuske** [comment]
I made one @eddyerburgh  😄
