### ISSUE TITLE
Route chunks does not works

### ISSUE THREAD

**Issue by ilajosmanov** [eddyerburgh/vue-cli-ssr-example#23]
When I run dev mode and go to :8080 ( ssr ) - i cannot route to another page because load async component was broken. (example: 0.js) But this file was created
<img width="727" alt="Снимок экрана 2019-03-09 в 15 39 30" src="https://user-images.githubusercontent.com/18512404/54072293-8d478600-4281-11e9-97de-d2c857a451fb.png">

In dev mode (ssr) hot reload does not work

In production mode - works.

**Comment by eddyerburgh** [comment]
The dev server runs on port 8081, so if you go to :8081 it should work fine.

The dev server actually starts two servers: a Webpack HMR server on port 8080 (that serves the HMR code), and the dev server on port  8081 for the dev server. I've added this to the README.
