### ISSUE TITLE
"These dependencies were not found" for all my dependencies

### ISSUE THREAD

**Issue by sneko** [eddyerburgh/vue-cli-ssr-example#28]
Hi,

I migrating my Vue project to match what you have done as SSR example but when running `npm run serve` I always get this error:
```
These dependencies were not found:

* fs in ./node_modules/winston/lib/winston/tail-file.js, ./node_modules/winston/lib/winston/transports/file.js
* http in ./node_modules/winston/lib/winston/transports/http.js
* https in ./node_modules/winston/lib/winston/transports/http.js
* os in ./node_modules/colors/lib/system/supports-colors.js, ./node_modules/winston/lib/winston/exception-handler.js and 3 others
* path in ./node_modules/winston/lib/winston/transports/file.js
* zlib in ./node_modules/winston/lib/winston/transports/file.js
```

After looking on internet I saw a solution of adding a setting to help in resolving (inside `vue.config.js`:

```
      resolve: {
        mainFields: [
          'fs',
        ],
        alias: {
          'create-api': createApiFile
        }
      }
```

The error just changed to all my other packages (that were not listed in the first error), so I guess it just solved something for `fs` but it doesn't finding the other packages.

Do you know what could be the problem please?

Thank you,

Note: it happens for both client and server serving/building

**Comment by eddyerburgh** [comment]
What Node and npm versions are you using?

**Comment by sneko** [comment]
Hi @eddyerburgh,

Node: v11.12.0
NPM: v6.7.0

But it's not longer a problem on my side, I just tried the following https://github.com/Akryum/vue-cli-plugin-ssr to migrate to SSR, by using it I no longer have an issue with Winston plugin. Also, since it embbeds most of specific Webpack code it's cleaner for me.

Thank you for your work, the Vue community is great :)
