### ISSUE TITLE
Making new changes does not seem to work?

### ISSUE THREAD

**Issue by Awais-cb** [eddyerburgh/vue-cli-ssr-example#6]
i have downloaded this example and tried to run on my machine but when make some change and try to re run it the old page appears up in the browser any way i can resolve this?

**Comment by eddyerburgh** [comment]
The project only supports client side HMR, which you enable by running:

```
npm run serve
```

**Comment by Mizumaki** [comment]
> Then the dev server will be running on port 8081

I can't find out where is the scripts which run the server on port 8081.

In your [package.json](https://github.com/eddyerburgh/vue-cli-ssr-example/blob/master/package.json), "npm run serve" runs `vue-cli-service serve` and `node scripts/start`.

However,  the port number of `vue-cli-service serve` is [8080](https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-serve), and `node scripts/start` is [8080](https://github.com/eddyerburgh/vue-cli-ssr-example/blob/master/scripts/start.js).

Where is the scripts which run the server on port 8081?
Thanks in advance.
