### ISSUE TITLE
how to test ssr is working? 

### ISSUE THREAD

**Issue by willi-dev** [eddyerburgh/vue-cli-ssr-example#9]
i was clone and try this project, but how i know if server side rendering is worked ? 

view page source (CTRL+U) or disable javascript ? 

Thanks.

**Comment by eddyerburgh** [comment]
I normally check the response in the network tab

**Comment by aghayeff** [comment]
Network tab doesn't show any SSR file. Do you save rendered html file which contains all html tags of view?
